### ISSUE TITLE
can not build success for ios

### ISSUE THREAD

**Issue by shipinbaoku** [pavzay/flutter_unity_mediation#1]
`/flutter/.pub-cache/hosted/pub.dartlang.org/unity_mediation-0.0.2/ios/Classes/ErrorUtils.swift:8:15: error: type 'UMSLoadError' has no member 'none'
            case .none:
                 ~^~~~
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
`

**Comment by pavelzaichyk** [comment]
Thanks for reporting the problem. It has been fixed in version 0.0.3
