### ISSUE TITLE
Please add banner ads - Unity also launched banner ads in  Mediation

### ISSUE THREAD

**Issue by Riyaz7364** [pavzay/flutter_unity_mediation#5]
Unity own banner ads are useless always no fill. Please add mediation banner ads so we can use other networks to show banner ads in the apps

**Comment by pavelzaichyk** [comment]
Unity Mediation SDK doesn't support banner ads yet

**Comment by Riyaz7364** [comment]
![Capture](https://user-images.githubusercontent.com/13451763/196029268-eff2c008-a2f7-4730-8328-6b49921d7dd1.PNG)

Unity add Banner ads in new SDK

**Comment by pavelzaichyk** [comment]
Banner Ads support is added in `unity_mediation: 0.1.0`
